# Generated by Django 5.2.12 on 2026-06-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='crop_height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='media',
            name='crop_width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='media',
            name='crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='crop_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediasuggestion',
            name='crop_height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='mediasuggestion',
            name='crop_width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mediasuggestion',
            name='crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediasuggestion',
            name='crop_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediasuggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
