# Generated by Django 5.2.17 on 2026-09-02 22:24

from django.db import migrations, models


def vaciar_imagenes_nulas(apps, schema_editor):
    """Deja en cadena vacía las portadas que estén en NULL.

    Los campos de imagen pasan a ser obligatorios en esta migración. Si alguna
    fila antigua tiene NULL, el ALTER TABLE a NOT NULL falla y la migración se
    cae a la mitad. Django guarda "sin imagen" como cadena vacía, no como NULL,
    así que normalizar antes deja la tabla lista para el cambio.
    """
    for modelo in ("Media", "MediaSuggestion"):
        apps.get_model("media", modelo).objects.filter(
            image__isnull=True
        ).update(image="")


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_media_crop_height_media_crop_width_media_crop_x_and_more"),
    ]

    operations = [
        # Debe ir ANTES de los AlterField que quitan null=True.
        migrations.RunPython(
            vaciar_imagenes_nulas,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="mediasuggestion",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="mediasuggestion",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="media",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="mediasuggestion",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="mediasuggestion",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
