# Generated by Django 5.2.17 on 2026-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_mediasuggestion_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="crop_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="media",
            name="crop_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="mediasuggestion",
            name="crop_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="mediasuggestion",
            name="crop_width",
            field=models.IntegerField(default=0),
        ),
    ]
