"""
Django settings for echoreviews_project project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# El valor por defecto solo sirve para desarrollo local. En producción se
# define DJANGO_SECRET_KEY como variable de entorno (ver .env.example).
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-!tlecf*c_0%l&_v*0@yc3l8x7r!b^_x!=ge76$%#nhi(w=5^n8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'hashtags',
    'media',
    'reviews',
    'users',
]

# Desde qué direcciones acepta el navegador hablar con esta API.
#
# Estaba fija en localhost:5173, y eso es la otra mitad exacta del problema que
# tenía el frontend con su dirección escrita a mano: aunque el sitio desplegado
# supiera dónde está la API, el navegador bloquearía cada petición por venir de
# un origen que esta lista no nombra. Las dos mitades tienen que salir del
# entorno o el despliegue no funciona.
#
# Ojo con el formato: van con esquema y sin barra final —"https://midominio.com",
# no "midominio.com" ni "https://midominio.com/"—. Es el error más común acá y
# falla en silencio, porque el rechazo lo hace el navegador y no Django.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "DJANGO_CORS_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173"
    ).split(",")
    if o.strip()
]

# El admin de Django sí usa cookies y CSRF, así que necesita conocer su propio
# origen público cuando corre detrás de HTTPS. Sin esto, iniciar sesión en
# /admin/ desde el dominio desplegado falla con "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'echoreviews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'echoreviews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
   "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "echoreviews_db"),
        "USER": os.getenv("DB_USER", "echoreviews_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "echoreviews_password"),
        "HOST": os.getenv("DB_HOST", "mysql"),
        "PORT": os.getenv("DB_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@echoreviews.local"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")

# Detrás de un proxy (Railway, Render, Fly…) el TLS lo termina el proxy y la
# petición llega a Django por HTTP plano. Sin esta línea `request.is_secure()`
# devuelve False aunque el visitante haya entrado por HTTPS, y las cookies
# marcadas como "solo por conexión segura" no se enviarían nunca.
#
# La cabecera la escribe el proxy, no el cliente; confiar en ella sin un proxy
# delante sería creerle a cualquiera que la mande, por eso solo tiene sentido
# en un despliegue que efectivamente esté detrás de uno.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Lo que `manage.py check --deploy` exige, activado solo cuando DEBUG está
# apagado. En desarrollo no hay HTTPS: encender esto en local dejaría el sitio
# redirigiendo a una dirección segura que no existe.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS le dice al navegador "de aquí en adelante, este dominio solo por
    # HTTPS", y lo recuerda durante este plazo. Es deliberadamente corto: si el
    # certificado falla, el navegador NO deja entrar y la única salida es
    # esperar a que venza. Un año, que es el valor habitual, convierte un error
    # de configuración en un sitio inaccesible durante un año.
    SECURE_HSTS_SECONDS = 3600

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "echoreviews.authentication.SoftJWTAuthentication",
    ),
    # drf-spectacular lee las vistas y genera el esquema OpenAPI solo. Se
    # prefiere a escribir la documentación a mano por una razón concreta: una
    # documentación escrita aparte envejece mal. Cambias un serializer, se te
    # olvida el archivo de docs, y a partir de ahí la documentación miente.
    # Generándola del código, no puede desincronizarse.
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API de EchoReviews",
    "DESCRIPTION": (
        "Reseñas de anime, música y videojuegos con moderación.\n\n"
        "Leer es público; escribir exige un token JWT en la cabecera "
        "`Authorization: Bearer <token>`, que se obtiene en `/api/token/`.\n\n"
        "Toda reseña habla de una obra: o una del catálogo, o una propuesta "
        "que espera aprobación. Las reseñas nacen en estado `pending` sin "
        "importar lo que mande el cliente, y un moderador decide si se "
        "publican o vuelven a su autor con un motivo."
    ),
    "VERSION": "1.0.0",
    # El esquema en bruto no se sirve dentro de la interfaz: para eso está la
    # ruta /api/schema/, y así la página de documentación carga más liviana.
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}