# Generated by Django 5.2.13 on 2026-04-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_status_alter_media_title_mediasuggestion'),
        ('reviews', '0002_alter_review_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='media_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediasuggestion'),
        ),
    ]
