# Generated by Django 5.2.17 on 2026-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
