# Generated by Django 5.2.17 on 2026-09-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_review_rejection_reason_alter_review_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
    ]
