# Generated by Django 5.2.13 on 2026-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_hashtag_status_hashtagsuggestion'),
        ('reviews', '0003_review_media_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagsuggestion',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.review'),
        ),
    ]
